### PR TITLE
Fix date parsing

### LINKED ISSUE #123: Wrong year when creating a tournament
If you create a tournament for Jan 1st 2015, it shows up as 2014.

bitballs___tournaments

### PR DESCRIPTION
**Pull request by jandjorgensen**
Fixes #123

### CODE REVIEW

File: public/models/player.js [hunk 1]
```diff
@@ -15,7 +16,7 @@ var Player = Map.extend({
 		jsBirthday: {
 			get: function(){
 				var date = this.attr("birthday");
-				return date ? new Date(date) : null;
+				return date ? toDate(date) : null;
```
Comment (justinbmeyer) [inline public/models/player.js]: could moment have been used here?

**Comment by justinbmeyer** [comment]
no tests.
