### PR TITLE
Fix arguments affected by call signature change

### LINKED ISSUE #126: Prevent moving video location on deleting a stat
When a stat is clicked on, it updates the video position.  This shouldn't happen when a stat is deleted.

You probably just need a `event.preventDefault()` somewhere.

Related: #58.

### PR DESCRIPTION
**Pull request by akagomez**
A last minute call signature change caused the `event` argument to be undefined, resulting in `event.stopPropagation` not getting called. 

By changing the call signature the event isn't propagated - meaning `gotoTimeMinus5` isn't called - the player isn't seeked in issue #126 and the error isn't thrown in issue #130. 

Closes #126, #130

### CODE REVIEW

File: public/components/game/details/details_test.js [hunk 1]
```diff
@@ -87,3 +87,36 @@ QUnit.test('A stat can be deleted by an admin', function () {
...
+
+    QUnit.stop();
+
+    var vm = $('game-details').viewModel();
+
+    vm.gotoTimeMinus5 = function () {
+        gotoCalled = true;
+    };
+
+    vm.bind('game', function(ev, game) {
```
Comment (akagomez) [inline public/components/game/details/details_test.js]: Remove
