### PR TITLE
Make ids match up with readme toc

### LINKED ISSUE #222: README url fragments don't work
Doesn't work: http://donejs.github.io/bitballs/docs/index.html#setup-environment
Works: https://github.com/donejs/bitballs/#setup-environment

### PR DESCRIPTION
**Pull request by ramblinjan**
Make ids match up with readme toc

Fixes #222

### CODE REVIEW

File: theme/static/content_list.js [hunk 1]
```diff
@@ -0,0 +1,91 @@
...
+			}
+		},
+		collectSignatures: function() {
+			var cloned = $('.content .signature').clone();
+			// remove release numbers
+			cloned.find(".release").remove();
+			return cloned;
+		},
+		collectHeadings: function() {
+			var depth = ( window.docObject.outline && window.docObject.outline.depth ) || 3;
```
Comment (jandjorgensen) [inline theme/static/content_list.js]: Change default depth for our page

File: theme/static/content_list.js [hunk 2]
```diff
@@ -0,0 +1,94 @@
...
+			
+			var headingStack = [],
+				last = function(){
+					return headingStack[ headingStack.length -1 ]
+				};
+			
+			var ch = this.collectHeadings().each(function(ix) {
+				var el = $(this);
+				//change formatting here from default to match this:
+				// ## This is My Heading --> <h2 id="this-is-my-heading">
```
Comment (jandjorgensen) [inline theme/static/content_list.js]: Changed from default here

File: theme/static/content_list.js [hunk 3]
```diff
@@ -0,0 +1,94 @@
...
+		},
+		collectSignatures: function() {
+			var cloned = $('.content .signature').clone();
+			// remove release numbers
+			cloned.find(".release").remove();
+			return cloned;
+		},
+		collectHeadings: function() {
+			//change the depth so we capture all our headings
+			var depth = ( window.docObject.outline && window.docObject.outline.depth ) || 3;
```
Comment (jandjorgensen) [inline theme/static/content_list.js]: Changed from default here

File: theme/static/content_list.js [hunk 4]
```diff
@@ -0,0 +1,94 @@
...
+					sections.push(section);
+					headingStack.push(section);
+				} else {
+					last().sections.push(section);
+					headingStack.push(section);
+				}	
+			});
+
+			// make sure to hide TOC, but still do id processing
+			if(window.docObject.hideContents){
```
Comment (jandjorgensen) [inline theme/static/content_list.js]: Changed from default here
